#!/usr/bin/env bash
set -euo pipefail

############################################################
# Mandatory variables

# Path to block flashed device
device=

hostname=arch
swap_size=500M
kernel_options="rw console=ttyS0"

timezone=Europe/Moscow
locales='
  en_US.UTF-8
  ru_RU.UTF-8
'
############################################################
# Optional variables
user_name=vlad
user_password=
root_password=
additional_packages=(
  linux-firmware amd-ucode intel-ucode
  iwd modemmanager
  git nano tree
)

mirrors='
  https://mirror.yandex.ru/archlinux/$repo/os/$arch
'
