#!/usr/bin/env bash
set -euo pipefail

############################################################
# Mandatory variables

# Path to block flashed device
device=

hostname=arch
swap_size=500M
kernel_options="rw console=ttyS0"

timezone=Europe/Moscow
locales='
  en_US.UTF-8
  ru_RU.UTF-8
'
############################################################
# Optional variables
user_name=vlad
user_password=
paswordless_sudo=false
root_password=
additional_packages=(
  linux-firmware amd-ucode intel-ucode iwd
  xorg-drivers
  git nano tree dra
)

mirrors='
  https://mirror.yandex.ru/archlinux/$repo/os/$arch
'

path_to_copy=

post_bash_script='\
# Mandatory variables
DEPLOY_CONFIGS_INSTANCE="INSTANCE_HERE"
USER_PASSWORD_FOR_SUDO="PASSWORD_HERE"

su vlad -c bash <<EOF
set -e

error() {
  echo "$@" >&2
  return 1
}

# Clones configuration
git clone https://github.com/backdround/configuration.git ~/configuration
cd ~/configuration

# Download deploy-configs
dra download --select "deploy-configs-linux-amd64-{tag}.tar.gz" backdround/deploy-configs
tar -xvf ./deploy-configs-linux-amd64-*.tar.gz
rm -rf ./deploy-configs-linux-amd64-*.tar.gz
mkdir -p ~/go/bin
mv deploy-configs ~/go/bin

# Deploys configs
~/go/bin/deploy-configs "$DEPLOY_CONFIGS_INSTANCE" || {
  error "Error occurs while deploying configs" || true
}

# Configurates system
./init.sh "$USER_PASSWORD_FOR_SUDO"
EOF
'
