#!/usr/bin/env bash
set -euo pipefail

############################################################
# Mandatory variables

# Path to block flashed device
device=

hostname=arch
swap_size=500M
kernel_options="rw console=ttyS0"

timezone=Europe/Moscow
locales='
  en_US.UTF-8
  ru_RU.UTF-8
'
############################################################
# Optional variables
user_name=vlad
user_password=
paswordless_sudo=false
root_password=
additional_packages=(
  linux-firmware amd-ucode intel-ucode iwd
  xorg-drivers
  git nano tree jq
)

mirrors='
  https://mirror.yandex.ru/archlinux/$repo/os/$arch
'

path_to_copy="./post-installation-utilities.sh"

post_bash_script='\
set -e

# Mandatory variables
DEPLOY_CONFIGS_INSTANCE="INSTANCE_HERE"
USER_PASSWORD_FOR_SUDO="PASSWORD_HERE"

mv /root/post-installation-utilities.sh /tmp

su vlad -c bash <<EOF
set -e
source /tmp/post-installation-utilities.sh

# Clones configuration
git clone https://github.com/backdround/configuration.git ~/configuration
cd ~/configuration

# Deploys configs
download-deploy-configs ~/go/bin/
~/go/bin/deploy-configs "$DEPLOY_CONFIGS_INSTANCE" || {
  error "Error occurs while deploying configs" || true
}

# Configurates system
./init.sh "$USER_PASSWORD_FOR_SUDO"
EOF
'
